#
# NOTE:
#   `xprop | grep WM_CLASS`
#   Use 2nd argument
#
#   https://picom.app/
#
# NOTE:
#   いやーまじでここの設定、分からんわ
#


log-level = "warn";

#
shadow = false;
shadow-radius = 8;
shadow-opacity = 1.00;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-color = "#ff7f7f";
crop-shadow-to-monitor = false;

#
fading = true;
fade-in-step = 0.020;
fade-out-step = 0.020;

#
opacity = 1.00;
frame-opacity = 1.00;

#
focus = false;
blur-background = false;
full-shadow = false;
redir-ignore = false;
# clip-shadow-above = false;


#
#
#
rules: (
  ##
  {
    match =
          "window_type = 'unknown'"
      " || window_type = 'desktop'"
      " || window_type = 'dock'"
      " || window_type = 'toolbar'"
      " || window_type = 'menu'"
      " || window_type = 'utility'"
      " || window_type = 'splash'"
      " || window_type = 'dialog'"
      " || window_type = 'normal'"
      " || window_type = 'dropdown_menu'"
      " || window_type = 'popup_menu'"
      " || window_type = 'tooltip'"
      " || window_type = 'notification'"
      " || window_type = 'combo'"
      " || window_type = 'dnd'"
      " || window_type = '_GTK_FRAME_EXTENTS@'";
    opacity = 1.00;
  },
  ##
  {
    match = "(
         class_g = 'kitty'
    ) && focused";
    opacity = 0.90;
    shadow = true;
  }, {
    match = "(
         class_g = 'kitty'
    ) && !focused";
    opacity = 0.50;
    shadow = true;
  },
  ##
  {
    match = "(
         class_g = 'firefox'
      || class_g = 'org.mozilla.Thunderbird'
      || class_g = 'KeePassXC'
    ) && focused";
    opacity = 0.95;
  }, {
    match = "(
         class_g = 'firefox'
      || class_g = 'org.mozilla.Thunderbird'
      || class_g = 'KeePassXC'
    ) && !focused";
    opacity = 0.95;
  },
  ##
  {
    match = "(
         class_g = 'Thunar'
      || class_g = 'Xfce4-settings-manager'
      || class_g = 'Org.xfce.mousepad'
      || class_g = 'dmenu'
      || class_g = 'code-oss'
      || class_g = 'Notable'
    ) && focused";
    opacity = 0.90;
  }, {
    match = "(
         class_g = 'Thunar'
      || class_g = 'Xfce4-settings-manager'
      || class_g = 'Org.xfce.mousepad'
      || class_g = 'dmenu'
      || class_g = 'code-oss'
      || class_g = 'Notable'
    ) && !focused";
    opacity = 0.90;
  }
)
