#
# NOTE: 
# `xprop | grep WM_CLASS`
# Use 2nd argument
#


log-level = "warn";
log-file = "/home/dollplayer/.local/share/picom.log"
# write-pid-path = "/path/to/your/log/file"


shadow-color = "#ff7f7f"

frame-opacity = 1.0;

rules: (
  ##
  {
    match = "(
         class_g = 'kitty'
    ) && focused";
    opacity = 0.9;
    corner-radius = 0;
  }, {
    match = "(
         class_g = 'kitty'
    ) && !focused";
    opacity = 0.5;
    corner-radius = 15;
  },
  ##
  {
    match = "(
         class_g = 'Alacritty'
      || class_g = 'Thunar'
      || class_g = 'org.gnome.Nautilus'
      || class_g = 'code-oss'
      || class_g = 'org.mozilla.Thunderbird'
      || class_g = 'Org.xfce.mousepad'
      || class_g = 'Notable'
      || class_g = 'KeePassXC'
    ) && focused";
    opacity = 0.9;
    corner-radius = 0;
  }, {
    match = "(
         class_g = 'Alacritty'
      || class_g = 'Thunar'
      || class_g = 'org.gnome.Nautilus'
      || class_g = 'code-oss'
      || class_g = 'org.mozilla.Thunderbird'
      || class_g = 'Org.xfce.mousepad'
      || class_g = 'Notable'
      || class_g = 'KeePassXC'
      || class_g = 'vlc'
    ) && !focused";
    opacity = 0.6;
    corner-radius = 5;
  },
  ##
  {
    match = "(
         class_g = 'vlc'
    ) && focused";
    opacity = 1.0;
    corner-radius = 0;
    shadow = false;
  }, {
    match = "(
         class_g = 'vlc'
    ) && !focused";
    opacity = 0.95;
    corner-radius = 0;
    shadow = false;
  },
  ##
  {
    match = "window_type = 'popup_menu'"
        " || window_type = 'dropdown_menu'"
        " || window_type = 'menu'"
    opacity = 1.0;
    shadow = false;
  },
  {
    match = "(
         class_g = 'firefox'
    ) && focused";
    opacity = 1.0;
    shadow = false;
  }, {
    match = "(
         class_g = 'firefox'
    ) && !focused";
    opacity = 1.0;
    shadow = false;
  }
)

